name: Backend

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
        
      - name: Generate gqlgen files
        run: go run github.com/99designs/gqlgen generate
        working-directory: ./backend
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: ./backend
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          files: backend/coverage.txt
