name: Frontend
on:
  push:
    branches:
      - 'main'
      - 'feat/fastlane_gha'
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npx expo prebuild
      - run: fastlane main_development
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        working-directory: ./frontend
