name: Frontend
on:
  push:
    branches:
      - 'main'
      - 'feat/fastlane_gha'
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: fastlane main_development
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        working-directory: ./frontend
